#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)
#
libs-$(CONFIG_LIB_SEL4_ARM_VMM) += libsel4arm-vmm

libsel4arm-vmm: common $(libc) libutils libsel4utils libsel4vka libsel4vspace libsel4dma
libsel4arm-vmm: libsel4simple libplatsupport

ifeq ($(CONFIG_LIB_USB),y)
libsel4arm-vmm: libusbdrivers
endif

ifeq ($(CONFIG_LIB_SEL4_ARM_VMM_VCHAN_SUPPORT),y)
libsel4arm-vmm: libsel4vchan
endif
